services:
  backend:
    container_name: tuning-backend
    image: hirouniv2409.azurecr.io/backend:development
    environment:
      DATABASE_URL: mysql://user:password@db/hirouniv-db
    ports:
      - "18080:8080"
    volumes:
      - ./backend:/usr/src/backend
    networks:
      - webapp-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:18080/api/health_check", "-X", "GET"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 600s
    entrypoint: ["sh", "-c", "cargo watch -x run"]

  frontend:
    container_name: tuning-frontend
    image: hirouniv2409.azurecr.io/frontend:development
    ports:
      - "13000:3000"
    volumes:
      - ./frontend:/usr/src/frontend
    networks:
      - webapp-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:13000/health-check", "-X", "GET"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 300s
    entrypoint: ["sh", "-c", "yarn install --frozen-lockfile && yarn dev"]

  db:
    container_name: tuning-mysql
    image: hirouniv2409.azurecr.io/mysql:latest
    user: 1000:1000
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: hirouniv-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/migration:/etc/mysql/migration
    networks:
      - webapp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 300s

  nginx:
    container_name: tuning-nginx
    image: hirouniv2409.azurecr.io/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
    networks:
      - webapp-network
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy

networks:
  webapp-network:
    external: true
